### PR TITLE
To Do List

### PR DESCRIPTION
**Pull request by karanJ2212**
Setted up a new project with webpack 
The index.html file set as a template using the HTML Webpack Plugin.
index.js file has an array of some simple to do tasks (array of objects). 
Function to iterate over the tasks array and populate an HTML list item element for each task.
Page load render the dynamically created list of tasks in the dedicated placeholder. 
 CSS loaded by Webpack Style/CSS Loader.

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Karan,
 
 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request
You have submitted a project, whereby some linter checks are failing on your Pull Request. Kindly ensure that **all** checks are passing and request another code review.

**Failing Checks:**
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @karanJ2212,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You do not have a README. Kindly add a README using [the required template](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by karanJ2212** [comment]
Readme.md added

**Review by TedLivist — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @karanJ2212,

Good job so far!
✔️ Good documentation
✔️ App is properly set up with webpack
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### I am requesting these changes here because the affected file is not present in the Files changed tab.
- [ ] In your `src/index.js` file your list of tasks is missing the correct attributes (description [string], index [integer], completed [boolean]). Your task is in this format:

  ```
  const task = [
      {
        desc: "buy fruits",
        id: 1,
      }
    ];
  ```
  But it should be like this:
  ```
  const task = [
      {
        description: "buy fruits",
        completed: false
        index: 1
      }
    ];

- [ ] Kindly style your app to match the layout provided in the video:

  Your Implementation | Required Design
  :---:|:---:
  ![ffuf](https://user-images.githubusercontent.com/36542986/206126200-18b6ef1e-00b5-4808-ac0f-d8a483f6da11.jpg) | ![image](https://user-images.githubusercontent.com/36542986/206126533-585b50c1-8cd9-4b80-b2f3-258598dc55e5.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by karanJ2212** [comment]
Made changes to style  app to match the layout provided in the video

list of tasks is now with the correct attributes (description [string], index [integer], completed [boolean])

**Review by jasonfelice — APPROVED** [review]
Hi @karanJ2212, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<p align="center"></p>

## Highlights
Good Design✔️

## Optional suggestions

- [ ]  [OPTIONAL]  You should not have `node_modules` committed to GitHub. Please add `node_modules` in your `.gitignore`. You can follow [this tutorial](https://medium.com/@buyananderson/accidentally-push-to-github-the-node-modules-without-ignoring-it-f766dad15eaa).

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
